project:
  type: website

website:
  title: "Daniel Thiele"
  navbar:
    left:
      - posts.qmd 
    search: false

format:
  html:
    theme: 
      - darkly
      - custom.scss
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto
